# Generated by Django 4.2.1 on 2023-06-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='Day',
            field=models.CharField(max_length=223),
        ),
    ]
